application: dartmouthlastchances
version: 1
runtime: python
api_version: 1

handlers:
- url: /static
  static_dir: static

- url: /pages
  static_dir: pages

- url: /match
  script: lastchances.py
  login: admin

- url: /mail
  script: lastchances.py
  login: admin

- url: /mailuser
  script: lastchances.py
  login: admin

- url: /addtestcrush
  script: lastchances.py
  login: admin

- url: /clearmemcache
  script: lastchances.py
  login: admin

- url: /clearall
  script: lastchances.py
  login: admin

- url: /crushedon
  script: lastchances.py
  login: admin

- url: /stats
  script: lastchances.py
  login: admin

- url: /_ah/queue/hothandler/.*
  script: hothandler.py
  login: admin

- url: /.*
  script: lastchances.py

builtins:
- datastore_admin: on
